name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      with:
        static_site_generator: next
        
    - name: Build with Next.js
      run: |
        export NEXT_PUBLIC_BASE_PATH="/dncl"
        export NEXT_PUBLIC_API_BASE_URL="https://solopg.com/next/dncl"
        export ESLINT_MODE=build
        export NODE_ENV=production
        echo "Testing with NEXT_PUBLIC_BASE_PATH='/dncl'"
        npm run build

    - name: Debug environment and build output
      run: |
        echo "=== Environment variables ==="
        echo "NEXT_PUBLIC_BASE_PATH: '$NEXT_PUBLIC_BASE_PATH'"
        echo "NEXT_PUBLIC_API_BASE_URL: '$NEXT_PUBLIC_API_BASE_URL'"
        echo "NODE_ENV: '$NODE_ENV'"
        echo ""
        echo "=== Directory structure after build ==="
        find . -type d -name "out" -o -name ".next" | head -5
        echo ""
        echo "=== Out directory contents ==="
        if [ -d "./out" ]; then
          find ./out -type f | head -20
        else
          echo "out directory does not exist!"
        fi
        echo ""
        echo "=== .next directory contents ==="
        if [ -d "./.next" ]; then
          ls -la ./.next/
        else
          echo ".next directory does not exist!"
        fi
        echo ""
        echo "=== Root directory contents ==="
        ls -la ./
        
    - name: Create CNAME file (only if out exists)
      run: |
        if [ -d "./out" ]; then
          echo "dncl.solopg.com" > ./out/CNAME
          echo "CNAME created in existing out directory"
        else
          mkdir -p ./out
          echo "dncl.solopg.com" > ./out/CNAME
          echo "Created out directory and CNAME file"
        fi
        ls -la ./out/
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4