name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      with:
        static_site_generator: next
        
    - name: Build with Next.js
      run: |
        export NEXT_PUBLIC_BASE_PATH=""
        export NEXT_PUBLIC_API_BASE_URL="https://solopg.com/next/dncl"
        export ESLINT_MODE=build
        npm run build

    - name: Debug root directory after build
      run: |
        echo "=== ルートディレクトリの全内容 ==="
        ls -la ./
        echo ""
        echo "=== outディレクトリの確認 ==="
        ls -la ./out/ 2>/dev/null || echo "outディレクトリは存在しません"
        echo ""
        echo "=== .nextディレクトリの確認 ==="
        ls -la ./.next/ | head -10
        echo ""
        echo "=== HTMLファイルの検索 ==="
        find . -name "*.html" -type f -maxdepth 3 | head -10
        echo ""
        echo "=== 可能性のあるビルド出力ディレクトリ ==="
        find . -type d -name "out" -o -name "dist" -o -name "build" -o -name "static" | head -10

    - name: Verify build output
      run: |
        if [ -d "./out" ]; then
          echo "✓ Build successful - out directory exists"
          echo "Contents:"
          find ./out -type f | head -10
        else
          echo "❌ Build failed - no out directory"
          exit 1
        fi

    - name: Add CNAME for custom domain
      run: |
        echo "dncl.solopg.com" > ./out/CNAME
        echo "✓ CNAME file created"
        echo "Final out directory contents:"
        ls -la ./out/ | head -10

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4